### ISSUE TITLE
Can't install with Swift Package Manager

### ISSUE THREAD

**Issue by kevinrenskers** [kennic/NKButton#4]
![Screen Shot 2020-10-02 at 16 48 21](https://user-images.githubusercontent.com/229384/94937607-16f81d80-04d0-11eb-8170-7af819fc07cc.png)

![Screen Shot 2020-10-02 at 16 49 15](https://user-images.githubusercontent.com/229384/94937613-195a7780-04d0-11eb-8a94-94524eca98a5.png)

**Comment by kennic** [comment]
Please select `Branch` instead
